# Numpy

optimized **LAPACK** and **BLAS** libraries for low-level vector, matrix, and linear algebra routines; or other specialized libraries

The **SciPy** organization and its web site www.scipy.org provide a
centralized resource for information about the core packages in the scientific Python ecosystem, and lists of additional specialized packages, as well as documentation and tutorials.

Another great resource is the **Numeric and Scientific** page on the official Python Wiki: http://wiki.python.org/moin/NumericAndScientific.

REPL: Read–Evaluate–Print–Loop

IPython is an enhanced command-line REPL environment for
Python, with additional features for interactive and exploratory computing.

The core of NumPy is implemented in C
and provides efficient functions for manipulating and processing arrays.

In [3]:
import numpy as np
print(np.__version__)
# help(np.ndarray)

1.20.1


The core of the NumPy library is the data structures for representing multidimensional arrays of homogeneous data. The main data structure for multidimensional arrays in NumPy is the **ndarray**. **ndarray** also contains important metadata about the array, such as its _shape_, _size_, _data type_, and other attributes.

In [13]:
data = np.array([ [1, 2], [3, 4], [5, 6] ])
print(type(data))
print(data)
print(data.ndim)
print(data.shape)
print(data.size)
print(data.dtype)
print(data.nbytes)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)
6
int64
48


### Basic Numpy Data Types

| dtype | Variants | Description |
|-------|----------|--------------|
|int | int8, int16, int32, int64 | Integers |
|uint | uint8, uint16, uint32, uint64 | Unsigned (nonnegative) integers |
|bool | Bool | Boolean (True or False) |
|float | float16, float32, float64, float128 | Floating-point numbers |
|complex | complex64, complex128, complex256 | Complex-valued floating-point numbers |

In [15]:
np.array([1, 2, 3, 4], dtype=np.int32)

array([1, 2, 3, 4], dtype=int32)

In [16]:
np.array([1, 2, 3], dtype=np.float32)

array([1., 2., 3.], dtype=float32)

In [17]:
np.array([1, 2, 3], dtype=np.complex64)

array([1.+0.j, 2.+0.j, 3.+0.j], dtype=complex64)

In [19]:
data = np.array([1, 2, 3], dtype=np.float32)
print(data)

[1. 2. 3.]


In [20]:
data.astype(np.int32)

array([1, 2, 3], dtype=int32)

A **NumPy** array can be specified to be stored in _row-major_ format, using the keyword argument `order='C'`, and column-major format, using the keyword argument `order='F'`, when the array is created or reshaped. The default format is _row-major_.

The NumPy array attribute ndarray.strides defines exactly how
this mapping is done. The strides attribute is a tuple of the same length as the number
of axes (dimensions) of the array. Each value in strides is the factor by which the index
for the corresponding axis is multiplied when calculating the memory offset (in bytes)
for a given index expression.

In [25]:
row_major=np.array([ [1, 2, 3], [4, 5, 6]], dtype=np.int32)
print(row_major.shape)
print(row_major.size)
print(row_major.strides)

(2, 3)
6
(12, 4)


In [28]:
col_major = np.array([ [1, 2, 3], [4, 5, 6]], dtype=np.int32, order='F')
print(col_major)
print(col_major.strides)

[[1 2 3]
 [4 5 6]]
(4, 8)
